name: push-images-to-quay
on:
  push:
    branches:
      - main
jobs:
  build:
    env:
      image_name: konflux-tooling
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Get image tags
        id: image_tags
        run: |
          echo -n ::set-output name=IMAGE_TAGS::
          TAGS=('latest')
          TAGS+=("${GITHUB_SHA}")
          TAGS+=("${GITHUB_SHA:0:7}")
          ( IFS=$','; echo "${TAGS[*]}" )

      - name: Build and publish image to Quay
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Containerfile
          push: true
          registry: quay.io
          repository: ${{ secrets.REGISTRY_REPOSITORY }}/${{ env.image_name }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          tags: "${{ steps.image_tags.outputs.IMAGE_TAGS }}"
